// Build script — generates src/gdrive_client.rs from env vars.
// Runs every build. Reads GDRIVE_CLIENT_ID + GDRIVE_CLIENT_SECRET.
// Output file is gitignored — secrets never touch source tree.
//
// Local dev: export env vars before `cargo build`
// CI: secrets injected via GitHub Actions secrets.

fn main() {
    println!("cargo:rerun-if-env-changed=GDRIVE_CLIENT_ID");
    println!("cargo:rerun-if-env-changed=GDRIVE_CLIENT_SECRET");

    let client_id = std::env::var("GDRIVE_CLIENT_ID")
        .unwrap_or_else(|_| "MISSING_GDRIVE_CLIENT_ID".to_string());
    let client_secret = std::env::var("GDRIVE_CLIENT_SECRET")
        .unwrap_or_else(|_| "MISSING_GDRIVE_CLIENT_SECRET".to_string());

    // Escape double quotes to be safe (shouldn't be any in real creds)
    let client_id_esc = client_id.replace('"', "\\\"");
    let client_secret_esc = client_secret.replace('"', "\\\"");

    let content = format!(
        "// AUTO-GENERATED by build.rs — DO NOT EDIT, DO NOT COMMIT.\n\
         // Source: GDRIVE_CLIENT_ID + GDRIVE_CLIENT_SECRET env vars at build time.\n\
         pub const CLIENT_ID: &str = \"{}\";\n\
         pub const CLIENT_SECRET: &str = \"{}\";\n",
        client_id_esc, client_secret_esc
    );

    std::fs::write("src/gdrive_client.rs", content)
        .expect("Failed to write src/gdrive_client.rs");
}
